"""
Complete Pipeline Script for NASA Crater Detection

This script demonstrates the full workflow:
1. Convert dataset to YOLO OBB format
2. Train the model
3. Run predictions on test data
4. Output results in competition CSV format

Usage:
    # Full pipeline
    python run_pipeline.py --mode all

    # Only convert dataset
    python run_pipeline.py --mode convert

    # Only train
    python run_pipeline.py --mode train

    # Only predict
    python run_pipeline.py --mode predict --model path/to/model.pt
"""

import argparse
import os
from pathlib import Path


def run_convert(args):
    """Convert dataset to YOLO OBB format."""
    from convert_to_yolo_obb import convert_dataset

    print("\n" + "="*60)
    print("Step 1: Converting Dataset to YOLO OBB Format")
    print("="*60 + "\n")

    convert_dataset(
        csv_path=args.csv,
        images_dir=args.images_dir,
        output_dir=args.yolo_dataset,
        train_ratio=args.train_ratio,
        copy_images=args.copy_images
    )

    # Update dataset.yaml with correct path
    yaml_path = Path(__file__).parent / 'dataset.yaml'
    yaml_content = f"""# NASA Crater Detection Dataset Configuration for YOLO OBB
# Auto-generated by run_pipeline.py

# Dataset root directory
path: {os.path.abspath(args.yolo_dataset)}

# Train/val/test splits (relative to 'path')
train: images/train
val: images/val

# Class names for crater classification
# Original values 2,3,4 are mapped to 0,1,2
names:
  0: crater_class_2
  1: crater_class_3
  2: crater_class_4

# Number of classes
nc: 3
"""
    with open(yaml_path, 'w') as f:
        f.write(yaml_content)

    print(f"\nDataset YAML updated: {yaml_path}")


def run_train(args):
    """Train YOLO OBB model."""
    from train import train

    print("\n" + "="*60)
    print("Step 2: Training YOLO OBB Model")
    print("="*60 + "\n")

    yaml_path = Path(__file__).parent / 'dataset.yaml'

    train(
        data=str(yaml_path),
        model=args.model_size,
        epochs=args.epochs,
        imgsz=args.imgsz,
        batch=args.batch,
        device=args.device,
        project=args.project,
        name=args.name,
        resume=args.resume,
        patience=args.patience,
    )


def run_predict(args):
    """Run predictions on test data."""
    from predict import CraterPredictor, save_predictions_csv

    print("\n" + "="*60)
    print("Step 3: Running Predictions")
    print("="*60 + "\n")

    # Find best model if not specified
    model_path = args.model
    if not model_path:
        default_path = Path(args.project) / args.name / 'weights' / 'best.pt'
        if default_path.exists():
            model_path = str(default_path)
        else:
            raise FileNotFoundError(
                f"No model found at {default_path}. "
                "Please specify --model or train a model first."
            )

    print(f"Using model: {model_path}")

    predictor = CraterPredictor(
        model_path=model_path,
        conf_threshold=args.conf,
        iou_threshold=args.iou,
        max_det=args.max_det,
        device=args.device
    )

    predictions = predictor.predict_directory(
        source_dir=args.test_dir,
        recursive=True
    )

    save_predictions_csv(
        predictions,
        args.output,
        include_confidence=args.include_confidence
    )

    print(f"\nPredictions complete! Output: {args.output}")


def main():
    parser = argparse.ArgumentParser(
        description='NASA Crater Detection Pipeline'
    )

    # Mode selection
    parser.add_argument(
        '--mode',
        choices=['all', 'convert', 'train', 'predict'],
        default='all',
        help='Pipeline mode: all, convert, train, or predict'
    )

    # Dataset conversion arguments
    parser.add_argument('--csv', default='../train-gt.csv', help='Path to train-gt.csv')
    parser.add_argument('--images-dir', default='../train', help='Path to training images')
    parser.add_argument('--yolo-dataset', default='../yolo_dataset', help='Output YOLO dataset directory')
    parser.add_argument('--train-ratio', type=float, default=0.8, help='Train/val split ratio')
    parser.add_argument('--copy-images', action='store_true', help='Copy images instead of symlinks')

    # Training arguments
    parser.add_argument('--model-size', default='yolov8n-obb.pt',
                       choices=['yolov8n-obb.pt', 'yolov8s-obb.pt', 'yolov8m-obb.pt',
                               'yolov8l-obb.pt', 'yolov8x-obb.pt'],
                       help='YOLO model size')
    parser.add_argument('--epochs', type=int, default=100, help='Training epochs')
    parser.add_argument('--imgsz', type=int, default=1024, help='Image size')
    parser.add_argument('--batch', type=int, default=8, help='Batch size')
    parser.add_argument('--device', default='', help='Device (0, 0,1, cpu)')
    parser.add_argument('--project', default='../runs/train', help='Project directory')
    parser.add_argument('--name', default='crater_obb', help='Experiment name')
    parser.add_argument('--resume', action='store_true', help='Resume training')
    parser.add_argument('--patience', type=int, default=50, help='Early stopping patience')

    # Prediction arguments
    parser.add_argument('--model', default='', help='Path to trained model for prediction')
    parser.add_argument('--test-dir', default='../test', help='Test images directory')
    parser.add_argument('--output', default='../predictions.csv', help='Output CSV path')
    parser.add_argument('--conf', type=float, default=0.25, help='Confidence threshold')
    parser.add_argument('--iou', type=float, default=0.45, help='IoU threshold')
    parser.add_argument('--max-det', type=int, default=100, help='Max detections per image')
    parser.add_argument('--include-confidence', action='store_true', help='Include confidence in CSV')

    args = parser.parse_args()

    # Change to script directory for relative paths
    os.chdir(Path(__file__).parent)

    if args.mode == 'all':
        run_convert(args)
        run_train(args)
        run_predict(args)
    elif args.mode == 'convert':
        run_convert(args)
    elif args.mode == 'train':
        run_train(args)
    elif args.mode == 'predict':
        run_predict(args)


if __name__ == '__main__':
    main()
